### ISSUE TITLE
cacheSize get wrong after hitting maxItems

### ISSUE THREAD

**Issue by trycoon** [ahume/tiny-ttl-cache#2]
In put():

```
if (!node) {
    // Check the cache size and prune if neccessary.
    if (this.cacheSize >= this.maxItems) {
        var keyToDelete = this.itemList.pop();
        delete this.cache[keyToDelete];
    }
    node = {};
    this.cacheSize = this.cacheSize + 1;
```

If we hit maxItems we remove the last item in the cache, but cacheSize is never decreased. Instead cacheSize is increased as if we didn't hit the limit. As the code works now it doesn't matter, but if we add a size()-function that returns the current size of the cache we would get the wrong result.

Suggestion is to add a "this.cacheSize = this.cacheSize - 1;" after the delete. Please correct me if I'm wrong!

**Comment by ahume** [comment]
Thanks for raising. How did you even notice this, given it doesn't cause an external bug (yet)? :)

**Comment by trycoon** [comment]
Well, thankfully the cache implementation does not span over so many lines of codes, so I just read the code from the first line to the last. And just happened to see the "bug". Thanks for fixing it so quickly, but could you please bump the version number in package.json also? Like, "1.1.0", so we get the fixed version downloaded.

**Comment by trycoon** [comment]
Or maybe "1.0.1" would be a better choice since there are no breaking changes and nothing new was introduced, just a bug fix. This could be your guideline: http://semver.org/

**Comment by ahume** [comment]
Bumped to 1.0.1.
